# DXCC country lookup table from Big CTY database
# Maps country names to DXCC numbers

DXCC_LOOKUP: dict[str, str] = {
    "Canada": "1",
    "Afghanistan": "3",
    "Agalega & St. Brandon": "4",
    "Aland Islands": "5",
    "Alaska": "6",
    "Albania": "7",
    "American Samoa": "9",
    "Amsterdam & St. Paul Is.": "10",
    "Andaman & Nicobar Is.": "11",
    "Anguilla": "12",
    "Antarctica": "13",
    "Armenia": "14",
    "Asiatic Russia": "15",
    "N.Z. Subantarctic Is.": "16",
    "Aves Island": "17",
    "Azerbaijan": "18",
    "Baker & Howland Islands": "20",
    "Balearic Islands": "21",
    "Palau": "22",
    "Bouvet": "24",
    "Belarus": "27",
    "Canary Islands": "29",
    "Central Kiribati": "31",
    "Ceuta & Melilla": "32",
    "Chagos Islands": "33",
    "Chatham Islands": "34",
    "Christmas Island": "35",
    "Clipperton Island": "36",
    "Cocos Island": "37",
    "Cocos (Keeling) Islands": "38",
    "Crete": "40",
    "Crozet Island": "41",
    "Desecheo Island": "43",
    "Dodecanese": "45",
    "East Malaysia": "46",
    "Easter Island": "47",
    "Eastern Kiribati": "48",
    "Equatorial Guinea": "49",
    "Mexico": "50",
    "Eritrea": "51",
    "Estonia": "52",
    "Ethiopia": "53",
    "European Russia": "54",
    "Fernando de Noronha": "56",
    "Bahamas": "60",
    "Franz Josef Land": "61",
    "Barbados": "62",
    "French Guiana": "63",
    "Bermuda": "64",
    "British Virgin Islands": "65",
    "Belize": "66",
    "Cayman Islands": "69",
    "Cuba": "70",
    "Galapagos Islands": "71",
    "Dominican Republic": "72",
    "El Salvador": "74",
    "Georgia": "75",
    "Guatemala": "76",
    "Grenada": "77",
    "Haiti": "78",
    "Guadeloupe": "79",
    "Honduras": "80",
    "Jamaica": "82",
    "Martinique": "84",
    "Nicaragua": "86",
    "Panama": "88",
    "Turks & Caicos Islands": "89",
    "Trinidad & Tobago": "90",
    "Aruba": "91",
    "Antigua & Barbuda": "94",
    "Dominica": "95",
    "Montserrat": "96",
    "St. Lucia": "97",
    "St. Vincent": "98",
    "Glorioso Islands": "99",
    "Argentina": "100",
    "Guam": "103",
    "Bolivia": "104",
    "Guantanamo Bay": "105",
    "Guernsey": "106",
    "Guinea": "107",
    "Brazil": "108",
    "Guinea-Bissau": "109",
    "Hawaii": "110",
    "Heard Island": "111",
    "Chile": "112",
    "Isle of Man": "114",
    "Colombia": "116",
    "ITU HQ": "117",
    "Jan Mayen": "118",
    "Ecuador": "120",
    "Jersey": "122",
    "Johnston Island": "123",
    "Juan de Nova & Europa": "124",
    "Juan Fernandez Islands": "125",
    "Kaliningrad": "126",
    "Guyana": "129",
    "Kazakhstan": "130",
    "Kerguelen Islands": "131",
    "Paraguay": "132",
    "Kermadec Islands": "133",
    "Kyrgyzstan": "135",
    "Peru": "136",
    "Republic of Korea": "137",
    "Kure Island": "138",
    "Suriname": "140",
    "Falkland Islands": "141",
    "Lakshadweep Islands": "142",
    "Laos": "143",
    "Uruguay": "144",
    "Latvia": "145",
    "Lithuania": "146",
    "Lord Howe Island": "147",
    "Venezuela": "148",
    "Azores": "149",
    "Australia": "150",
    "Macao": "152",
    "Macquarie Island": "153",
    "Nauru": "157",
    "Vanuatu": "158",
    "Maldives": "159",
    "Tonga": "160",
    "Malpelo Island": "161",
    "New Caledonia": "162",
    "Papua New Guinea": "163",
    "Mauritius": "165",
    "Mariana Islands": "166",
    "Market Reef": "167",
    "Marshall Islands": "168",
    "Mayotte": "169",
    "New Zealand": "170",
    "Mellish Reef": "171",
    "Pitcairn Island": "172",
    "Micronesia": "173",
    "Midway Island": "174",
    "French Polynesia": "175",
    "Fiji": "176",
    "Minami Torishima": "177",
    "Moldova": "179",
    "Mount Athos": "180",
    "Mozambique": "181",
    "Navassa Island": "182",
    "Solomon Islands": "185",
    "Niger": "187",
    "Niue": "188",
    "Norfolk Island": "189",
    "Samoa": "190",
    "North Cook Islands": "191",
    "Ogasawara": "192",
    "Annobon Island": "195",
    "Palmyra & Jarvis Islands": "197",
    "Peter 1 Island": "199",
    "Pr. Edward & Marion Is.": "201",
    "Puerto Rico": "202",
    "Andorra": "203",
    "Revillagigedo": "204",
    "Ascension Island": "205",
    "Vienna Intl Ctr": "206",
    "Rodriguez Island": "207",
    "Belgium": "209",
    "Sable Island": "211",
    "Bulgaria": "212",
    "St. Martin": "213",
    "Corsica": "214",
    "Cyprus": "215",
    "San Andres & Providencia": "216",
    "San Felix & San Ambrosio": "217",
    "Sao Tome & Principe": "219",
    "Denmark": "221",
    "Faroe Islands": "222",
    "England": "223",
    "Finland": "224",
    "Sardinia": "225",
    "France": "227",
    "Fed. Rep. of Germany": "230",
    "Somalia": "232",
    "Gibraltar": "233",
    "South Cook Islands": "234",
    "South Georgia Island": "235",
    "Greece": "236",
    "Greenland": "237",
    "South Orkney Islands": "238",
    "Hungary": "239",
    "South Sandwich Islands": "240",
    "South Shetland Islands": "241",
    "Iceland": "242",
    "Ireland": "245",
    "Sov Mil Order of Malta": "246",
    "Spratly Islands": "247",
    "Italy": "248",
    "St. Kitts & Nevis": "249",
    "St. Helena": "250",
    "Liechtenstein": "251",
    "St. Paul Island": "252",
    "St. Peter & St. Paul": "253",
    "Luxembourg": "254",
    "Madeira Islands": "256",
    "Malta": "257",
    "Svalbard": "259",
    "Monaco": "260",
    "Tajikistan": "262",
    "Netherlands": "263",
    "Northern Ireland": "265",
    "Norway": "266",
    "Poland": "269",
    "Tokelau Islands": "270",
    "Portugal": "272",
    "Trindade & Martim Vaz": "273",
    "Tristan da Cunha & Gough Islands": "274",
    "Romania": "275",
    "Tromelin Island": "276",
    "St. Pierre & Miquelon": "277",
    "San Marino": "278",
    "Scotland": "279",
    "Turkmenistan": "280",
    "Spain": "281",
    "Tuvalu": "282",
    "UK Base Areas on Cyprus": "283",
    "Sweden": "284",
    "US Virgin Islands": "285",
    "Uganda": "286",
    "Switzerland": "287",
    "Ukraine": "288",
    "United Nations HQ": "289",
    "United States": "291",
    "Uzbekistan": "292",
    "Vietnam": "293",
    "Wales": "294",
    "Vatican City": "295",
    "Serbia": "296",
    "Wake Island": "297",
    "Wallis & Futuna Islands": "298",
    "West Malaysia": "299",
    "Western Kiribati": "301",
    "Western Sahara": "302",
    "Willis Island": "303",
    "Bahrain": "304",
    "Bangladesh": "305",
    "Bhutan": "306",
    "Costa Rica": "308",
    "Myanmar": "309",
    "Cambodia": "312",
    "Sri Lanka": "315",
    "China": "318",
    "Hong Kong": "321",
    "India": "324",
    "Indonesia": "327",
    "Iran": "330",
    "Iraq": "333",
    "Israel": "336",
    "Japan": "339",
    "Jordan": "342",
    "DPR of Korea": "344",
    "Brunei Darussalam": "345",
    "Kuwait": "348",
    "Lebanon": "354",
    "Mongolia": "363",
    "Nepal": "369",
    "Oman": "370",
    "Pakistan": "372",
    "Philippines": "375",
    "Qatar": "376",
    "Saudi Arabia": "378",
    "Seychelles": "379",
    "Singapore": "381",
    "Djibouti": "382",
    "Syria": "384",
    "Taiwan": "386",
    "Thailand": "387",
    "Asiatic Turkey": "390",
    "United Arab Emirates": "391",
    "Algeria": "400",
    "Angola": "401",
    "Botswana": "402",
    "Burundi": "404",
    "Cameroon": "406",
    "Central African Republic": "408",
    "Cape Verde": "409",
    "Chad": "410",
    "Comoros": "411",
    "Republic of the Congo": "412",
    "Dem. Rep. of the Congo": "414",
    "Benin": "416",
    "Gabon": "420",
    "The Gambia": "422",
    "Ghana": "424",
    "Cote d'Ivoire": "428",
    "Kenya": "430",
    "Lesotho": "432",
    "Liberia": "434",
    "Libya": "436",
    "Madagascar": "438",
    "Malawi": "440",
    "Mali": "442",
    "Mauritania": "444",
    "Morocco": "446",
    "Nigeria": "450",
    "Zimbabwe": "452",
    "Reunion Island": "453",
    "Rwanda": "454",
    "Senegal": "456",
    "Sierra Leone": "458",
    "Rotuma Island": "460",
    "South Africa": "462",
    "Namibia": "464",
    "Sudan": "466",
    "Kingdom of Eswatini": "468",
    "Tanzania": "470",
    "Tunisia": "474",
    "Egypt": "478",
    "Burkina Faso": "480",
    "Zambia": "482",
    "Togo": "483",
    "Conway Reef": "489",
    "Banaba Island": "490",
    "Yemen": "492",
    "Croatia": "497",
    "Slovenia": "499",
    "Bosnia-Herzegovina": "501",
    "North Macedonia": "502",
    "Czech Republic": "503",
    "Slovak Republic": "504",
    "Pratas Island": "505",
    "Scarborough Reef": "506",
    "Temotu Province": "507",
    "Austral Islands": "508",
    "Marquesas Islands": "509",
    "Palestine": "510",
    "Timor - Leste": "511",
    "Chesterfield Islands": "512",
    "Ducie Island": "513",
    "Montenegro": "514",
    "Swains Island": "515",
    "St. Barthelemy": "516",
    "Curacao": "517",
    "Sint Maarten": "518",
    "Saba & St. Eustatius": "519",
    "Bonaire": "520",
    "Republic of South Sudan": "521",
    "Republic of Kosovo": "522",
}


def get_dxcc_number(country_name: str) -> str | None:
    """Look up DXCC number by country name. Returns None if not found."""
    if not country_name:
        return None
    return DXCC_LOOKUP.get(country_name)


def resolve_dxcc(dx_country: str, adif: str | None = None) -> str:
    """Resolve DXCC number for a station. Tries ADIF first, then country name lookup."""
    if adif:
        adif_stripped = adif.strip()
        if adif_stripped:
            return adif_stripped.lstrip("0") or ""
    if dx_country:
        return get_dxcc_number(dx_country) or ""
    return ""
